import { PRODUCT_IMAGES } from "./images";

export const FALLBACK_PRODUCTS = [
  {
    _id: "fb1",
    name: "Fresh Oranges 1kg — Vitamin-C Pack",
    description: "Premium supermarket oranges, perfect for daily nutrition and family meals.",
    price: 4.99,
    originalPrice: 6.99,
    stock: 120,
    rating: 5,
    isFlashSale: true,
    image: PRODUCT_IMAGES.orange,
    category: { _id: "fruit", name: "Fruit & Produce" },
  },
  {
    _id: "fb2",
    name: "Organic Strawberries 500g",
    description: "Fresh berry pack from trusted supermarket suppliers.",
    price: 5.49,
    originalPrice: 7.99,
    stock: 80,
    rating: 5,
    isFlashSale: true,
    image: PRODUCT_IMAGES.strawberry,
    category: { _id: "fruit", name: "Fruit & Produce" },
  },
  {
    _id: "fb3",
    name: "Green Bell Peppers 3-Pack",
    description: "Crisp peppers stocked daily in our produce aisle.",
    price: 3.29,
    originalPrice: 4.49,
    stock: 95,
    rating: 4,
    isFlashSale: true,
    image: PRODUCT_IMAGES.pepper,
    category: { _id: "veg", name: "Fresh Vegetables" },
  },
  {
    _id: "fb4",
    name: "Organic Kale Bunch",
    description: "Healthy greens available for online supermarket delivery.",
    price: 2.99,
    originalPrice: 3.99,
    stock: 60,
    rating: 5,
    isFlashSale: true,
    image: PRODUCT_IMAGES.kale,
    category: { _id: "veg", name: "Fresh Vegetables" },
  },
  {
    _id: "fb5",
    name: "Vine-Ripened Tomatoes 1kg",
    description: "Supermarket-quality tomatoes for cooking and salads.",
    price: 3.49,
    originalPrice: 4.99,
    stock: 110,
    rating: 4,
    image: PRODUCT_IMAGES.tomato,
    category: { _id: "veg", name: "Fresh Vegetables" },
  },
  {
    _id: "fb6",
    name: "Seasonal Pumpkin Each",
    description: "Fresh pumpkin from local supermarket suppliers.",
    price: 6.99,
    originalPrice: 8.99,
    stock: 40,
    rating: 5,
    image: PRODUCT_IMAGES.pumpkin,
    category: { _id: "veg", name: "Fresh Vegetables" },
  },
  {
    _id: "fb7",
    name: "Fresh Garlic 200g",
    description: "Pantry essential stocked in our grocery aisle.",
    price: 1.99,
    originalPrice: 2.49,
    stock: 200,
    rating: 5,
    image: PRODUCT_IMAGES.garlic,
    category: { _id: "pantry", name: "Pantry Staples" },
  },
  {
    _id: "fb8",
    name: "Broccoli Florets 500g",
    description: "Nutritious broccoli delivered from our online supermarket.",
    price: 3.79,
    originalPrice: 4.99,
    stock: 75,
    rating: 4,
    image: PRODUCT_IMAGES.broccoli,
    category: { _id: "veg", name: "Fresh Vegetables" },
  },
];
